### ISSUE TITLE
`Unknown encoding dict`

### ISSUE THREAD

**Issue by multimeric** [ilia-kats/MuData#2]
First of all, thanks for writing this, pure-R IO for anndata is going to be incredibly useful!

I have some anndata files that I created with R (using `zellkonverter`, so they might be a bit unusual). When I try to load them, I get the following:

```R
> MuData::readH5AD("/vast/scratch/users/milton.m/cache/R/CuratedAtlasQueryR/0.2/original/6d526063e52b119fc18ac359cc7a5667.h5ad")
Error in .local(x, ..., value) : 
  replacement 'metadata' value must be a list
In addition: Warning message:
In read_group(h5autoclose(view & "uns")) : Unknown encoding dict
```

It fails right at the end of `read_modality`:
https://github.com/ilia-kats/MuData/blob/0108b354a37786943d06900e143a7412fd0d7fee/R/read_h5mu.R#L256

Any idea what's going wrong here? When I try to explore the file with `h5ls`, I get:
```bash
$ h5ls --data /vast/scratch/users/milton.m/cache/R/CuratedAtlasQueryR/0.2/original/6d526063e52b119fc18ac359cc7a5667.h5ad/uns/ 
X_name                   Dataset {SCALAR}
    Data:
        (0) "X"
```
I'm not really sure what this means, but it doesn't look like a dictionary to me.

**Comment by ilia-kats** [comment]
The "unknown encoding dict" is just a warning, the actual error is `replacement 'metadata' value must be a list`. My guess is that your anndata file was created with anndata 0.8, which changed the on-disk format. We haven't yet had time to adapt MuData. If that is not the case, it would be helpful if you could upload the anndata file somewhere for us to debug.

**Comment by multimeric** [comment]
Thanks for the info. I probably did use anndata 0.8, since I created this file very recently. I'll see if an older anndata produces a compatible file.

But on that note, would it be easy to update MuData to support the new format? If it is, I'd be happy to contribute. The only concrete change I can see is the introduction of `encoding_type` and `encoding_version` to the group metadata.

**Comment by ilia-kats** [comment]
It shouldn't be too complicated, mainly just time. The main change is that now, every element has an econding type and version, including dense arrays and scalars. 0.8 also supports nullable arrays (so R's `NA` can now be represented) and there are changes to how categorical arrays (factors) are stored. The current format specification is [here](https://anndata.readthedocs.io/en/latest/fileformat-prose.html).

**Comment by multimeric** [comment]
I think the first, more important step is just being compatible with *reading* new AnnData files. And currently it seems like it will be quite an easy fix.

**Comment by ilia-kats** [comment]
There is now experimental read-write support for the new format in the anndata08 branch. Please give it a try and see if it works for you.
